# numpy

In [2]:
# creating numpy array 
import numpy as np


In [3]:
#single dimensional array
arr=np.array([1,2,4,5,6])
arr

array([1, 2, 4, 5, 6])

In [5]:
arr.ndim

1

In [6]:
#creating 2d array
two_d_array=np.array([[1,2,3,4],[5,6,7,8]])
two_d_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
two_d_array.ndim

2

In [8]:
two_d_array.dtype

dtype('int32')

In [14]:
array_example=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
array_example

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [11]:
array_example.dtype

dtype('int32')

In [12]:
array_example.ndim

2

In [15]:
array_example.shape

(2, 7)

### accessing element

In [16]:
array_example[1,3]

11

In [17]:
array_example[0,5]

6

In [19]:
#accesing row
array_example[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#accesing column
array_example[:,1]

array([2, 9])

# zeros and ones in  numpy

In [21]:
zero=np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [22]:
one=np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
full_var=np.full((3,3),30)
full_var

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [30]:
#create random aarray
random_number=np.random.rand(1,4)
random_number

array([[0.44109939, 0.97357774, 0.40963468, 0.68785591]])

In [33]:
array_example=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
array_example

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])